apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flask-application
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./production/ # change for each environment
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-series
  validation: client
