apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: Bucket
metadata:
  name: flask
  namespace: flux-system
spec:
  interval: 5m
  provider: generic
  bucketName: example
  endpoint: 192.168.0.11:4566
  insecure: true
  secretRef:
    name: s3-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: flux-system
type: Opaque
data:
  accesskey: RkFLRQ== 
  secretkey: RkFLRQ== 
